ota:
  - platform: esphome
    on_begin:
      - light.turn_off:
          id: display_backlight
          transition_length: 0s
      - lambda: "id(display_backlight).loop();"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

psram:
  speed: 80MHz
  mode: octal

wifi:
  reboot_timeout: 30min
  enable_btm: true
  enable_rrm: true

spi:
  - id: lcd_spi
    clk_pin: GPIO48
    mosi_pin: GPIO47

i2c:
  id: touchscreen_bus
  sda: GPIO19
  scl:
    number: GPIO45
    ignore_strapping_warning: true

output:
  - platform: ledc
    id: backlight_output
    pin: GPIO38
    frequency: 150Hz
    min_power: 0.01
    zero_means_zero: true

display:
  - platform: st7701s
    id: tft_display
    dimensions:
      width: 480
      height: 480
    # rotation: 270
    spi_mode: MODE3
    data_rate: 2MHz
    color_order: RGB
    invert_colors: False
    cs_pin: 39
    de_pin: 18
    hsync_pin: 16
    vsync_pin: 17
    pclk_pin: 21
    pclk_frequency: 12MHz
    pclk_inverted: False
    hsync_pulse_width: 8
    hsync_front_porch: 10
    hsync_back_porch: 20
    vsync_pulse_width: 8
    vsync_front_porch: 10
    vsync_back_porch: 10
    update_interval: never
    auto_clear_enabled: False
    init_sequence:
      - 1
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x10] # CMD2_BKSEL_BK0
      - [0xCD, 0x00] # disable MDT flag
    data_pins:
      red: [11, 12, 13, 14, 0]
      green: [8, 20, 3, 46, 9, 10]
      blue: [4, 5, 6, 7, 15]

touchscreen:
  - platform: gt911
    id: tft_touch
    display: tft_display
    # transform:
      # swap_xy: true
      # mirror_x: true
    on_release:
      - if:
          condition: lvgl.is_paused
          then:
          - lvgl.resume:
          - lvgl.widget.redraw:
          - light.turn_on:
              id: display_backlight
              transition_length: 300ms

light:
  - platform: monochromatic
    name: Háttérfény
    id: display_backlight
    output: backlight_output
    restore_mode: ALWAYS_ON
    default_transition_length: 1s

debug:
  update_interval: 60s

sensor:
  - platform: debug
    free:
      name: Heap Free
    block:
      name: Heap Max Block
    loop_time:
      name: Loop Time
    psram:
      name: PSRAM Free

time:
  - platform: sntp
    id: time_comp
    timezone: Europe/Budapest
    servers: 
      - 172.22.215.254
      - 172.22.215.254
      - 172.22.215.254

script:
  - id: set_display_idle
    then:
      - if:
          condition: 
            binary_sensor.is_on: bs_night_mode
          then:
            - light.turn_off:
                id: display_backlight
                transition_length: 2500ms
            - lvgl.pause:
          else:
            - if:
                condition: lvgl.is_paused
                then:
                  - lvgl.resume:
                  - lvgl.widget.redraw:
            - light.turn_on:
                id: display_backlight
                transition_length: 1500ms
                brightness: !lambda "return (id(display_brightness_idle).state / 100);"

lvgl:
  buffer_size: 12%
  rotation: 270
